/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wmh.project.algorithm.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import wmh.project.framework.DialogDisplayer;

/**
 *
 * @author MAREK
 */
public class AlgorithmSettingsUI extends javax.swing.JPanel implements ActionListener{

    private static AlgorithmSettingsUI me;
    
    /**
     * Creates new form AlgorithmSettingsUI
     */
    private AlgorithmSettingsUI() {
        initComponents();
        
        runButt.addActionListener(this);
    }
    
    public static AlgorithmSettingsUI getInstance(){
        if(me == null){
            me = new AlgorithmSettingsUI();
        }
        return me;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        graphPanel = new javax.swing.JPanel();
        graphScroll = new javax.swing.JScrollPane();
        graphLabel = new javax.swing.JLabel();
        runButt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("wmh/project/algorithm/ui/Bundle").getString("AlgorithmSettingsUI.jLabel1.text"), new Object[] {})); // NOI18N

        graphPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphScroll)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        graphLabel.setBackground(new java.awt.Color(231, 231, 183));
        graphLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        graphLabel.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("wmh/project/algorithm/ui/Bundle").getString("AlgorithmSettingsUI.graphLabel.text"), new Object[] {})); // NOI18N
        graphLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        graphLabel.setOpaque(true);

        runButt.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("wmh/project/algorithm/ui/Bundle").getString("AlgorithmSettingsUI.runButt.text"), new Object[] {})); // NOI18N

        jLabel2.setBackground(new java.awt.Color(231, 231, 183));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("wmh/project/algorithm/ui/Bundle").getString("AlgorithmSettingsUI.jLabel2.text"), new Object[] {})); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(graphLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(runButt)))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(runButt)
                .addGap(47, 47, 47)
                .addComponent(graphLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel graphLabel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollPane graphScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton runButt;
    // End of variables declaration//GEN-END:variables

    public void setEagleView(JComponent view){
        graphScroll.setViewportView(view);
    }
    
    public void clearEagleView(){
        graphScroll.setViewportView(null);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        DialogDisplayer.showSimpleInformation("TO DO: implement");
    }
}
