/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wmh.project.framework.explorer;

/**
 *
 * @author MAREK
 */
public class ExplorerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExplorerPanel
     */
    public ExplorerPanel() {
        initComponents();
        
        explorerScroll.setViewportView(Explorer.getDefault());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        explorerScroll = new javax.swing.JScrollPane();
        explorerLabel = new javax.swing.JLabel();

        mainPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(explorerScroll, java.awt.BorderLayout.CENTER);

        explorerLabel.setBackground(new java.awt.Color(231, 231, 183));
        explorerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        explorerLabel.setText("Data Explorer");
        explorerLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        explorerLabel.setOpaque(true);
        mainPanel.add(explorerLabel, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel explorerLabel;
    private javax.swing.JScrollPane explorerScroll;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
